export const types = {
  IS_LOADING: 'IS_LOADING',
  GET_ERRORS: 'GET_ERRORS',
  CLEARS_ERRORS: 'CLEARS_ERRORS',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  VERIFY_ACCOUNT_SUCCESS: 'VERIFY_ACCOUNT_SUCCESS',
  APPROVE_DOCS_SUCCESS: 'APPROVE_DOCS_SUCCESS',
};
